#!/bin/sh

sqlite=`which sqlite3`
db_path=/var/db/pkgdb/local.sqlite
pkg_path=/var/db/pkg

if [ ! -f "$sqlite" ]
then
    echo "Please install sqlite3 (/usr/ports/databases/sqlite3)"
    exit
fi

if [ ! -f "$db_path" ]
then
    echo "DB file not found"
    exit
fi

if [ "$(ls -A $pkg_path)" ]; then
    rm -r $pkg_path/*
fi
pkg_list=`$sqlite $db_path "SELECT name || '-' || version FROM packages;"`
for row in $pkg_list
do
    mkdir $pkg_path/$row    
done

if [ $# -eq 0 ]
then
    $sqlite $db_path "SELECT name || '-' || version FROM packages ORDER BY name;"
    exit
fi

case "$1" in
-La) 
    $sqlite $db_path "SELECT path FROM files;"
    ;;
-L) 
    $sqlite $db_path "SELECT f.path FROM files f JOIN packages p ON f.package_id = p.id WHERE (p.name || '-' || p.version) = '$2';"
    ;;
update)
    ;;    
*)
    echo "Parameter \"$1\" is not developed"
    ;;
esac
